language: java

jdk:
  - oraclejdk11

notifications:
  email:
    recipients:
      - horridge@stanford.edu
    on_success: never
    on_failure: always

before_install:
  - "export DISPLAY=:99.0"

services:
  - xvfb

script: 
  - mvn verify -B
